import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    /* }: Readonly<{ */
    /*   children: React.ReactNode; */
    /* }>) { */
    return (
        <html lang="en">
            <body>
                <main>
                    <nav>
                        <Link href="/stock">
                            Stock
                        </Link>
                        <Link href="/">
                            Home
                        </Link>
                    </nav>

                    {children}
                </main>
            </body>
        </html>
    );
}
